fix errors
git-svn-id: svn://svn.h5l.se/heimdal/trunk/heimdal@23544 ec53bebd-3082-4978-b11e-865c3cabbd6b

diff --git a/tests/gss/check-context.in b/tests/gss/check-context.in
--- a/tests/gss/check-context.in
+++ b/tests/gss/check-context.in
@@ -85,7 +85,7 @@ ${kadmin} ext -k ${keytab} host/lucid@${R} || exit 1
 
 ${kadmin} add -p p1 --use-defaults host/ok-delegate.test.h5l.se@${R} || exit 1
 ${kadmin} mod --attributes=+ok-as-delegate host/ok-delegate.test.h5l.se@${R} || exit 1
-
+${kadmin} ext -k ${keytab} host/ok-delegate.test.h5l.se@${R} || exit 1
 
 ${kadmin} add -p kaka --use-defaults digest/${R}@${R} || exit 1
 
@@ -130,12 +130,12 @@ echo "checking non existant keytabfile (krb5)"
 ${context} --mech-type=krb5 host@lucid.test.h5l.se  > test_context.log 2>&1 && \
 	{ exitcode=1 ; echo "test failed"; }
 grep ${keytabfile} test_context.log > /dev/null || \
-	{ exitcode=1 ; echo "test failed"; }
+	{ exitcode=1 ; echo "string missing failed"; }
 echo "checking non existant keytabfile (spengo)"
 ${context} --mech-type=spnego host@lucid.test.h5l.se > test_context.log 2>&1 && \
 	{ exitcode=1 ; echo "test failed"; }
 grep ${keytabfile} test_context.log > /dev/null || \
-	{ exitcode=1 ; echo "test failed"; }
+	{ exitcode=1 ; echo "string missing failed"; }
 
 mv ${keytabfile}.no ${keytabfile}
 
@@ -260,14 +260,7 @@ ${context} \
     --name-type=hostbased-service host@lucid.test.h5l.se || \
 	{ exitcode=1 ; echo "test failed"; }
 
-echo "ok-as-delegate not used"
-${context} \
-    --mech-type=krb5 \
-    --policy-delegate \
-    --name-type=hostbased-service host@lucid.test.h5l.se || \
-	{ exitcode=1 ; echo "test failed"; }
-
-echo "ok-as-delegate not used"
+echo "host without ok-as-delegate with policy-delegate"
 ${context} \
     --mech-type=krb5 \
     --policy-delegate \
@@ -279,21 +272,28 @@ echo "ok-as-delegate used by policy"
 ${context} \
     --mech-type=krb5 \
     --policy-delegate \
-    --name-type=hostbased-service ok-delegate.test.h5l.se || \
+    --name-type=hostbased-service host@ok-delegate.test.h5l.se || \
 	{ exitcode=1 ; echo "test failed"; }
-
 
 echo "Getting client initial tickets with --ok-as-delgate"
 ${kinit} --ok-as-delegate  --forwardable \
     --password-file=${objdir}/foopassword user1@${R} || exitcode=1
 
+echo "policy delegate to non delegate host"
+${context} \
+    --mech-type=krb5 \
+    --policy-delegate \
+    --server-no-delegate \
+    --name-type=hostbased-service host@lucid.test.h5l.se || \
+	{ exitcode=1 ; echo "test failed"; }
+
 echo "ok-as-delegate"
 ${context} \
     --mech-type=krb5 \
     --delegate \
-    --server-no-delegate \
     --name-type=hostbased-service host@lucid.test.h5l.se || \
 	{ exitcode=1 ; echo "test failed"; }
+
 
 echo "======time diffs between client and server"
 
