automatically bring up interfaces that we manage. This allows ctdb to work without requiring two IPs per public interface (This used to be ctdb commit 221850dcf9c28698eb3a1baf33cbf7f9137ac502)

diff --git a/ctdb/config/events b/ctdb/config/events
--- a/ctdb/config/events
+++ b/ctdb/config/events
@@ -28,6 +28,10 @@ case $cmd in
 	ip=$2
 	maskbits=$3
 
+	/sbin/ip link set $iface up || {
+		 echo "`/bin/date` Failed to bringup interface $iface"
+		 exit 1
+	}
 	/sbin/ip addr add $ip/$maskbits dev $iface || {
 		 echo "`/bin/date` Failed to add $ip/$maskbits on dev $iface"
 		 exit 1
