40.vsftpd monitor event only fails after 2 failures to connect to port 21.
Change the monitor event in 40.vsftpd so it only fails if there are 2
successive failures connecting to port 21.  This reduces the
likelihood of unhealthy nodes due to vsftpd being restarted for
reconfiguration due to node failover or system reconfiguration.

New eventscript functions ctdb_counter_init, ctdb_counter_incr,
ctdb_counter_limit.  These are used to count arbitrary things in
eventscripts, depending on the eventscript name and a tag that is
passed, and determine if a specified limit has been hit.  They're good
for counting failures!

These functions are used in 40.vsftpd and also in 01.reclock - the
latter used to do the counting without these functions.

Signed-off-by: Martin Schwenke <martin@meltin.net>

(This used to be ctdb commit cfe63636a163730ae9ad3554b78519b3c07d8896)

diff --git a/ctdb/config/functions b/ctdb/config/functions
--- a/ctdb/config/functions
+++ b/ctdb/config/functions
@@ -498,6 +498,40 @@ remove_ip() {
 }
 
 ########################################################
+# some simple logic for counting events - per eventscript
+# usage: ctdb_counter_init <tag>
+#        ctdb_counter_incr <tag>
+#        ctdb_counter_limit <tag> <limit>
+#        e.g. <tag> = "fail-count"
+# ctdb_counter_limit succeeds when count >= <limit>
+########################################################
+_ctdb_counter_common () {
+    _tag="$1"
+    _eventscript="${0##*/}" # basename
+
+    _counter_file="$CTDB_BASE/state/${_eventscript}-${_tag}"
+    mkdir -p "${_counter_file%/*}" # dirname
+}
+ctdb_counter_init () {
+    _ctdb_counter_common "$1"
+
+    echo -n > "$_counter_file"
+}
+ctdb_counter_incr () {
+    _ctdb_counter_common "$1"
+
+    # unary counting!
+    echo -n 1 >> "$_counter_file"
+}
+ctdb_counter_limit () {
+    _ctdb_counter_common "$1"
+    _limit="$2"
+
+    # unary counting!
+    _size=$(stat -c "%s" "$_counter_file" 2>/dev/null || echo 0)
+    [ $_size -ge $_limit ]
+}
+########################################################
 # load a site local config file
 ########################################################
 
