check winbind in monitoring event too (This used to be ctdb commit bccba656c21d0edbd9840401a3c43a76b1b3bc05)

diff --git a/ctdb/config/functions b/ctdb/config/functions
--- a/ctdb/config/functions
+++ b/ctdb/config/functions
@@ -162,3 +162,17 @@ ctdb_check_tcp_ports() {
       }
   done
 }
+
+######################################################
+# check a command returns zero status
+# usage: ctdb_check_command SERVICE_NAME <command>
+######################################################
+ctdb_check_command() {
+  service_name="$1"
+  wait_cmd="$2"
+  [ -z "$wait_cmd" ] && return;
+  $wait_cmd > /dev/null 2>&1 || {
+      echo "`date` ERROR: $service_name - $wait_cmd returned error"
+      exit 1
+  }
+}
