Eventscripts - new function ctdb_check_args()
Pass this "$@" to do common eventscript argument checking.

For regular use putting this in 00.ctdb would be enough.  However, for
developer testing it can be useful to call this in other eventscripts.
For example, 10.interfaces and 13.per_ip_routing currently check these
by hand.

Signed-off-by: Martin Schwenke <martin@meltin.net>

(This used to be ctdb commit 36de7e7fd6dfeed61ef9977b8d5b568f90a9707b)

diff --git a/ctdb/config/functions b/ctdb/config/functions
--- a/ctdb/config/functions
+++ b/ctdb/config/functions
@@ -83,6 +83,26 @@ debug ()
 }
 
 ##############################################################
+# check number of args for different events
+ctdb_check_args ()
+{
+    case "$1" in
+	takeip|releaseip)
+	    if [ $# != 4 ]; then
+		echo "ERROR: must supply interface, IP and maskbits"
+		exit 1
+	    fi
+	    ;;
+	updateip)
+	    if [ $# != 5 ]; then
+		echo "ERROR: must supply old interface, new interface, IP and maskbits"
+		exit 1
+	    fi
+	    ;;
+    esac
+}
+
+##############################################################
 # determine on what type of system (init style) we are running
 detect_init_style() {
     # only do detection if not already set:
