allow for probing of directories without raising an error
(This used to be ctdb commit 8fed021d11160b137f4140ea02947347250e2959)

diff --git a/ctdb/config/functions b/ctdb/config/functions
--- a/ctdb/config/functions
+++ b/ctdb/config/functions
@@ -145,19 +145,32 @@ ctdb_check_rpc() {
 
 ######################################################
 # check a set of directories is available
+# return 0 on a missing directory
+# usage: ctdb_check_directories_probe SERVICE_NAME <directories...>
+######################################################
+ctdb_check_directories_probe() {
+  service_name="$1"
+  shift
+  wait_dirs="$*"
+  [ -z "$wait_dirs" ] && return;
+  for d in $wait_dirs; do
+      [ -d $d ] || return 1
+  done
+  return 0
+}
+
+######################################################
+# check a set of directories is available
 # usage: ctdb_check_directories SERVICE_NAME <directories...>
 ######################################################
 ctdb_check_directories() {
   service_name="$1"
   shift
   wait_dirs="$*"
-  [ -z "$wait_dirs" ] && return;
-  for d in $wait_dirs; do
-      [ -d $d ] || {
-	  echo "ERROR: $service_name directory $d not available"
-	  exit 1
-      }
-  done
+  ctdb_check_directories_probe "$service_name" $wait_dirs || {
+      echo "ERROR: $service_name directory $d not available"
+      exit 1
+  }
 }
 
 ######################################################
