move the kill_tcp_connections() function from 10.interfaces to functions
(This used to be ctdb commit 055948530fb16bf49c42fc4489f29a21665156c0)

diff --git a/ctdb/config/functions b/ctdb/config/functions
--- a/ctdb/config/functions
+++ b/ctdb/config/functions
@@ -183,3 +183,43 @@ ctdb_check_command() {
       exit 1
   }
 }
+
+################################################
+# kill off any TCP connections with the given IP
+################################################
+kill_tcp_connections() {
+    _IP="$1"    
+    _failed=0
+
+    _killcount=0
+    connfile="$CTDB_BASE/state/connections.$_IP"
+    netstat -tn |egrep "^tcp.*\s+$_IP:.*ESTABLISHED" | awk '{print $4" "$5}' > $connfile
+    while read dest src; do
+	srcip=`echo $src | cut -d: -f1`
+	srcport=`echo $src | cut -d: -f2`
+	destip=`echo $dest | cut -d: -f1`
+	destport=`echo $dest | cut -d: -f2`
+	ctdb killtcp $srcip:$srcport $destip:$destport >/dev/null 2>&1 || _failed=1
+	echo "`date` Killing TCP connection $srcip:$srcport $destip:$destport"
+	_killcount=`expr $_killcount + 1`
+    done < $connfile
+    /bin/rm -f $connfile
+    [ $_failed = 0 ] || {
+	echo "`date` Failed to send killtcp control"
+	return;
+    }
+    [ $_killcount -gt 0 ] || {
+	return;
+    }
+    _count=0
+    while netstat -tn |egrep "^tcp.*\s+$_IP:.*ESTABLISHED" > /dev/null; do
+	sleep 1
+	_count=`expr $_count + 1`
+	[ $_count -gt 3 ] && {
+	    echo "`date` Timed out killing tcp connections for IP $_IP"
+	    return;
+	}
+    done
+    echo "`date` killed $_killcount TCP connections to released IP $_IP"
+}
+
