selftest: Reformat shell scripts
shfmt -f selftest/ | xargs shfmt -w -p -i 0 -fn

Signed-off-by: Andreas Schneider <asn@samba.org>
Reviewed-by: Andrew Bartlett <abartlet@samba.org>

diff --git a/selftest/gdb_backtrace b/selftest/gdb_backtrace
--- a/selftest/gdb_backtrace
+++ b/selftest/gdb_backtrace
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-BASENAME=`basename $0`
+BASENAME=$(basename $0)
 
 unset LD_PRELOAD
 
@@ -11,14 +11,13 @@ fi
 
 if [ "x$PLEASE_NO_GDB_BACKTRACE" != "x" ]; then
 	echo "${BASENAME}: Not running debugger because PLEASE_NO_GDB_BACKTRACE is set"
-        exit 0
+	exit 0
 fi
-
 
 # we want everything on stderr, so the program is not disturbed
 exec 1>&2
 
-UNAME=`uname`
+UNAME=$(uname)
 
 PID=$1
 BINARY=$2
@@ -30,31 +29,31 @@ test x"${PID}" = x"" && {
 
 DB_LIST="gdb"
 case "${UNAME}" in
-	#
-	# on Tru64 we need to try ladebug first
-	# because gdb crashes itself...
-	#
-	OSF1)
-		DB_LIST="ladebug ${DB_LIST}"
+#
+# on Tru64 we need to try ladebug first
+# because gdb crashes itself...
+#
+OSF1)
+	DB_LIST="ladebug ${DB_LIST}"
 	;;
-	#
-	# On solaris dbx is working way more better than gdb
-	# let's try it first
-	#
-	SunOS)
-		DB_LIST="dbx ${DB_LIST}"
+#
+# On solaris dbx is working way more better than gdb
+# let's try it first
+#
+SunOS)
+	DB_LIST="dbx ${DB_LIST}"
 	;;
-	#
-	# FreeBSD comes with a flavor that works gdb66 and one that don't gdb
-	# (gdb 6.1) let's try it first the one that works !
-	#
-	FreeBSD)
-		DB_LIST="gdb66 ${DB_LIST}"
+#
+# FreeBSD comes with a flavor that works gdb66 and one that don't gdb
+# (gdb 6.1) let's try it first the one that works !
+#
+FreeBSD)
+	DB_LIST="gdb66 ${DB_LIST}"
 	;;
 esac
 
 for DB in ${DB_LIST}; do
-	DB_BIN=`which ${DB} 2>/dev/null | grep '^/'`
+	DB_BIN=$(which ${DB} 2>/dev/null | grep '^/')
 	test x"${DB_BIN}" != x"" && {
 		break
 	}
@@ -68,59 +67,59 @@ test x"${DB_BIN}" = x"" && {
 need_binary="no"
 case "${DB}" in
 # These debuggers need the process binary specified:
-	ladebug)
+ladebug)
 	need_binary="yes"
 	;;
-	gdb66)
+gdb66)
 	need_binary="yes"
 	;;
-	dbx)
+dbx)
 	need_binary="yes"
 	;;
 esac
 
 test x"${need_binary}" = x"yes" && {
 
-# we first try to use /proc/${PID}/exe or /proc/{$PID}/path for solaris
-# then fallback to the binary from the commandline
-# then we search for the commandline argument with
-# 'which'
-#
+	# we first try to use /proc/${PID}/exe or /proc/{$PID}/path for solaris
+	# then fallback to the binary from the commandline
+	# then we search for the commandline argument with
+	# 'which'
+	#
 	test -f "/proc/${PID}/exe" && BINARY="/proc/${PID}/exe"
-	test -f "/proc/${PID}/path/a.out" && BINARY=`ls -l /proc/${PID}/path/a.out |sed 's/.*-> //'`
+	test -f "/proc/${PID}/path/a.out" && BINARY=$(ls -l /proc/${PID}/path/a.out | sed 's/.*-> //')
 	test x"${BINARY}" = x"" && BINARY="/proc/${PID}/exe"
-	test -f "${BINARY}" || BINARY=`which ${BINARY}`
-	
+	test -f "${BINARY}" || BINARY=$(which ${BINARY})
+
 	test -f "${BINARY}" || {
-	    echo "${BASENAME}: ERROR: Cannot find binary '${BINARY}'."
-	    exit 1
+		echo "${BASENAME}: ERROR: Cannot find binary '${BINARY}'."
+		exit 1
 	}
 }
 
-BATCHFILE_PRE=`mktemp --tmpdir gdb_backtrace_pre.XXXXXXXXXX`
+BATCHFILE_PRE=$(mktemp --tmpdir gdb_backtrace_pre.XXXXXXXXXX)
 test -n "${BATCHFILE_PRE}" || {
 	echo "mktemp doesn't work" 1>&2
 	exit 1
 }
-BATCHFILE_MAIN=`mktemp --tmpdir gdb_backtrace_main.XXXXXXXXXX`
+BATCHFILE_MAIN=$(mktemp --tmpdir gdb_backtrace_main.XXXXXXXXXX)
 test -n "${BATCHFILE_MAIN}" || {
 	echo "mktemp doesn't work" 1>&2
 	exit 1
 }
 case "${DB}" in
-	ladebug)
-cat << EOF  > ${BATCHFILE_PRE}
+ladebug)
+	cat <<EOF >${BATCHFILE_PRE}
 set \$stoponattach
 EOF
 
-cat << EOF  > ${BATCHFILE_MAIN}
+	cat <<EOF >${BATCHFILE_MAIN}
 where
 quit
 EOF
 	${DB_BIN} -c "${BATCHFILE_MAIN}" -i "${BATCHFILE_PRE}" -pid "${PID}" "${BINARY}"
 	;;
-	gdb66)
-cat << EOF  > ${BATCHFILE_MAIN}
+gdb66)
+	cat <<EOF >${BATCHFILE_MAIN}
 set height 1000
 bt full
 info locals
@@ -129,15 +128,15 @@ quit
 EOF
 	${DB_BIN} -x "${BATCHFILE_MAIN}" "${BINARY}" "${PID}"
 	;;
-	gdb)
-cat << EOF  > ${BATCHFILE_MAIN}
+gdb)
+	cat <<EOF >${BATCHFILE_MAIN}
 set height 0
 bt full
 thread apply all bt full
 info locals
 quit
 EOF
-	${DB_BIN} -batch -x "${BATCHFILE_MAIN}" --pid "${PID}" < /dev/null
+	${DB_BIN} -batch -x "${BATCHFILE_MAIN}" --pid "${PID}" </dev/null
 	;;
 dbx)
 	${DB_BIN} "where;dump;kill;quit" "${BINARY}" "${PID}"
