script: Reformat shell scripts
shfmt -f script/ | xargs shfmt -w -p -i 0 -fn

Signed-off-by: Andreas Schneider <asn@samba.org>
Reviewed-by: Andrew Bartlett <abartlet@samba.org>

diff --git a/script/git-hooks/pre-commit-hook b/script/git-hooks/pre-commit-hook
--- a/script/git-hooks/pre-commit-hook
+++ b/script/git-hooks/pre-commit-hook
@@ -3,13 +3,13 @@
 set -eu
 
 gitdir=$(git rev-parse --show-toplevel)
-if [ $? -ne 0 ] ; then
-    echo "git rev-parse --show-toplevel failed"
-    exit 1
+if [ $? -ne 0 ]; then
+	echo "git rev-parse --show-toplevel failed"
+	exit 1
 fi
 
-if [ ! -f ${gitdir}/script/git-hooks/pre-commit-script ] ; then
-    exit 0
+if [ ! -f ${gitdir}/script/git-hooks/pre-commit-script ]; then
+	exit 0
 fi
 
 ${gitdir}/script/git-hooks/pre-commit-script || exit $?
diff --git a/script/git-hooks/pre-commit-script b/script/git-hooks/pre-commit-script
--- a/script/git-hooks/pre-commit-script
+++ b/script/git-hooks/pre-commit-script
@@ -9,9 +9,9 @@ set -eu
 unset GIT_LITERAL_PATHSPECS
 
 gitdir=$(git rev-parse --show-toplevel)
-if [ $? -ne 0 ] ; then
-    echo "git rev-parse --show-toplevel failed"
-    exit 1
+if [ $? -ne 0 ]; then
+	echo "git rev-parse --show-toplevel failed"
+	exit 1
 fi
 
 ${gitdir}/script/git-hooks/check-trailing-whitespace || exit $?
