ctdb-tools: Fix get_nodes_with_status()
onnode usually has the surprising feature that it works on nodes
without CTDB installed.  This is useful for test nodes or when
interacting with local_daemons.sh - in the latter case, onnode is not
run on a node but needs to be tricked.

This works when specifying a PNN, range or list of PNNs, all or any.
However, it doesn't work when specifying a node status.  This is
because get_nodes_with_status() runs "ctdb -X status" directly.  This
currently fails under local_daemons.sh (except when used in a Samba
testenv such as clusteredmember where CTDB_SOCKET is set to point to
the first node's socket) .

Instead, run "ctdb -X status" under onnode recursively on the leader
node, which is most likely to have the best idea of all node states.
There is a precedent in the implementation of the "any" target, which
also run onnode recursively.

Doing the above causes onnode unit tests involving status-based
targets (e.g. healthy/ok, connected/con) to break.  There are 2
reasons for this, both involving the limited implementation of test
stubs:

* ssh currently just prints its inputs, which is OK for basic test
  cases.  However, when used recursively from onnode, it actually
  needs to run the ctdb stub.

* ctdb only handles producing the output of "ctdb -X status", which is
  set as input as part of the test setup.  Due to the above ssh
  change, the ctdb stub needs to return sane output for the leader
  command.

Reworking the above stubs keeps the tests working.

BUG: https://bugzilla.samba.org/show_bug.cgi?id=16267

Signed-off-by: Martin Schwenke <mschwenke@ddn.com>
Reviewed-by: Pavel Filipenský <pfilipensky@samba.org>

diff --git a/ctdb/tests/UNIT/onnode/stubs/ctdb b/ctdb/tests/UNIT/onnode/stubs/ctdb
--- a/ctdb/tests/UNIT/onnode/stubs/ctdb
+++ b/ctdb/tests/UNIT/onnode/stubs/ctdb
@@ -2,18 +2,46 @@
 
 # Fake ctdb client for onnode tests.
 
+# This is an include file, so commands are reachable by sourcing this file
+# shellcheck disable=SC2317
+
 out="${CTDB_TEST_TMP_DIR}/ctdb.out"
-if [ -r "$out" ]; then
+if [ ! -r "$out" ]; then
+	echo "Internal error: ctdb status -X output not setup"
+	exit 1
+fi
+
+ctdb_status_X()
+{
 	cat "$out"
 
 	rc="${CTDB_TEST_TMP_DIR}/ctdb.rc"
 	if [ -r "$rc" ]; then
 		exit "$(cat "$rc")"
 	fi
+}
 
-	exit 0
-fi
+leader()
+{
+	# Get 1st active node
+	_leader=$(awk -F'|' '$10 == 0 { print $2; exit }' "$out")
+	if [ -z "$_leader" ]; then
+		_leader="UNKNOWN"
+	fi
+	echo "$_leader"
+}
 
-echo "fake ctdb: no implementation for \"$*\""
+case "$*" in
+-X\ status)
+	ctdb_status_X
+	;;
+leader)
+	leader
+	;;
+*)
+	echo "fake ctdb: no implementation for \"$*\""
+	exit 1
+	;;
+esac
 
-exit 1
+exit 0
diff --git a/ctdb/tools/onnode b/ctdb/tools/onnode
--- a/ctdb/tools/onnode
+++ b/ctdb/tools/onnode
@@ -154,14 +154,26 @@ get_pnn_ctdb_cmd()
 	return 1
 }
 
+get_leader_pnn()
+{
+	get_pnn_ctdb_cmd "leader"
+}
+
 ctdb_status_output="" # cache
 get_nodes_with_status()
 {
 	local all_nodes="$1"
 	local status="$2"
 
+	local leader
+	if ! leader=$(get_leader_pnn); then
+		echo "${prog}: unable to get leader node" >&2
+		echo "${prog}: unable to get status of CTDB nodes" >&2
+		exit 1
+	fi
+
 	if [ -z "$ctdb_status_output" ]; then
-		ctdb_status_output=$(ctdb -X status 2>&1)
+		ctdb_status_output=$($0 "$leader" ctdb -X status 2>&1)
 		# No! Checking the exit code afterwards is actually clearer...
 		# shellcheck disable=SC2181
 		if [ $? -ne 0 ]; then
