s3:script: Reformat shell scripts
shfmt -f source3/script/ | xargs shfmt -w -p -i 0 -fn

Signed-off-by: Andreas Schneider <asn@samba.org>
Reviewed-by: Andrew Bartlett <abartlet@samba.org>

Autobuild-User(master): Andrew Bartlett <abartlet@samba.org>
Autobuild-Date(master): Thu Mar  3 01:53:16 UTC 2022 on sn-devel-184

diff --git a/source3/script/smbtar b/source3/script/smbtar
--- a/source3/script/smbtar
+++ b/source3/script/smbtar
@@ -14,20 +14,21 @@
 # being backed up.
 
 case $0 in
-    # when called by absolute path, assume smbclient is in the same directory
-    /*)
-	SMBCLIENT="`dirname $0`/smbclient";;
-    *)  # you may need to edit this to show where your smbclient is
-	SMBCLIENT="smbclient";;
+# when called by absolute path, assume smbclient is in the same directory
+/*)
+	SMBCLIENT="$(dirname $0)/smbclient"
+	;;
+*) # you may need to edit this to show where your smbclient is
+	SMBCLIENT="smbclient" ;;
 esac
 
 # These are the default values. You could fill them in if you know what
 # you're doing, but beware: better not store a plain text password!
 server=""
-service="backup"            # Default: a service called "backup"
+service="backup" # Default: a service called "backup"
 password=""
-username=$LOGNAME           # Default: same user name as in *nix
-verbose="2>/dev/null"        # Default: no echo to stdout
+username=$LOGNAME     # Default: same user name as in *nix
+verbose="2>/dev/null" # Default: no echo to stdout
 log="-d 2"
 newer=""
 newerarg=""
@@ -39,10 +40,11 @@ tarargs=""
 cdcmd="\\"
 tapefile=${TAPE-tar.out}
 
-Usage(){
-    ex=$1
-    shift
-echo >&2 "Usage: `basename $0` [<options>] [<include/exclude files>]
+Usage()
+{
+	ex=$1
+	shift
+	echo >&2 "Usage: $(basename $0) [<options>] [<include/exclude files>]
 Function: backup/restore a Windows PC directories to a local tape file
 Options:         (Description)                 (Default)
   -r             Restore from tape file to PC  Save from PC to tapefile
@@ -53,114 +55,127 @@ Options:         (Description)                 (Default)
   -p <password>  Specify PC Password           $password
   -x <share>     Specify PC Share              $service
   -X             Exclude mode                  Include
-  -N <newer>     File for date comparison      `set -- $newer; echo $2`
-  -b <blocksize> Specify tape's blocksize      `set -- $blocksize; echo $2`
+  -N <newer>     File for date comparison      $(
+		set -- $newer
+		echo $2
+	)
+  -b <blocksize> Specify tape's blocksize      $(
+		set -- $blocksize
+		echo $2
+	)
   -d <dir>       Specify a directory in share  $cdcmd
-  -l <log>       Specify a Samba Log Level     `set -- $log; echo $2`
+  -l <log>       Specify a Samba Log Level     $(
+		set -- $log
+		echo $2
+	)
   -u <user>      Specify User Name             $username
   -t <tape>      Specify Tape device           $tapefile
 "
-  echo >&2 "$@"
-  exit $ex
+	echo >&2 "$@"
+	exit $ex
 }
 
 # echo Params count: $#
 
-# DEC OSF AKA Digital UNIX does not seem to return a value in OPTIND if 
+# DEC OSF AKA Digital UNIX does not seem to return a value in OPTIND if
 # there are no command line params, so protect us against that ...
 if [ $# = 0 ]; then
 
-  Usage 2 "Please enter a command line parameter!"
+	Usage 2 "Please enter a command line parameter!"
 
 fi
 
 while getopts riavl:b:d:N:s:p:x:u:Xt: c; do
-  case $c in
-   r) # [r]estore to Windows (instead of the default "Save from Windows")
-      tarcmd="x"
-      ;;
-   i) # [i]ncremental
-      tarargs=${tarargs}ga
-      clientargs="-c 'tarmode inc'"
-      ;;
-   a) # [a]rchive
-      tarargs=${tarargs}a
-      ;;
-   l) # specify [l]og file
-      log="-d $OPTARG"
-      case "$OPTARG" in
-	[0-9]*) ;;
-	*)      echo >&2 "$0: Error, log level not numeric: -l $OPTARG"
-		exit 1
-      esac
-      ;;
-   d) # specify [d]irectory to change to in server's share
-      cdcmd="$OPTARG"
-      ;;
-   N) # compare with a file, test if [n]ewer
-      if [ -f $OPTARG ]; then
-	newer=$OPTARG
-	newerarg="N"
-      else
-	echo >&2 $0: Warning, $OPTARG not found
-      fi
-      ;;
-   X) # Add exclude flag
-      tarargs=${tarargs}X
-      ;;
-   s) # specify [s]erver's share to connect to - this MUST be given.
-      server="$OPTARG"
-      ;;
-   b) # specify [b]locksize
-      blocksize="$OPTARG"
-      case "$OPTARG" in
-	[0-9]*) ;;
-	*)      echo >&2 "$0: Error, block size not numeric: -b $OPTARG"
-		exit 1
-      esac
-      blocksizearg="b"
-      ;;
-   p) # specify [p]assword to use
-      password="$OPTARG"
-      ;;
-   x) # specify windows [s]hare to use
-      service="$OPTARG"
-      ;;
-   t) # specify [t]apefile on local host
-      tapefile="$OPTARG"
-      ;;
-   u) # specify [u]sername for connection
-      username="$OPTARG"
-      ;;
-   v) # be [v]erbose and display what's going on
-      verbose=""
-      tarargs=${tarargs}v
-      ;;
-   '?') # any other switch
-       Usage 2 "Invalid switch specified - abort."
-      ;;
-  esac
+	case $c in
+	r) # [r]estore to Windows (instead of the default "Save from Windows")
+		tarcmd="x"
+		;;
+	i) # [i]ncremental
+		tarargs=${tarargs}ga
+		clientargs="-c 'tarmode inc'"
+		;;
+	a) # [a]rchive
+		tarargs=${tarargs}a
+		;;
+	l) # specify [l]og file
+		log="-d $OPTARG"
+		case "$OPTARG" in
+		[0-9]*) ;;
+		*)
+			echo >&2 "$0: Error, log level not numeric: -l $OPTARG"
+			exit 1
+			;;
+		esac
+		;;
+	d) # specify [d]irectory to change to in server's share
+		cdcmd="$OPTARG"
+		;;
+	N) # compare with a file, test if [n]ewer
+		if [ -f $OPTARG ]; then
+			newer=$OPTARG
+			newerarg="N"
+		else
+			echo >&2 $0: Warning, $OPTARG not found
+		fi
+		;;
+	X) # Add exclude flag
+		tarargs=${tarargs}X
+		;;
+	s) # specify [s]erver's share to connect to - this MUST be given.
+		server="$OPTARG"
+		;;
+	b) # specify [b]locksize
+		blocksize="$OPTARG"
+		case "$OPTARG" in
+		[0-9]*) ;;
+		*)
+			echo >&2 "$0: Error, block size not numeric: -b $OPTARG"
+			exit 1
+			;;
+		esac
+		blocksizearg="b"
+		;;
+	p) # specify [p]assword to use
+		password="$OPTARG"
+		;;
+	x) # specify windows [s]hare to use
+		service="$OPTARG"
+		;;
+	t) # specify [t]apefile on local host
+		tapefile="$OPTARG"
+		;;
+	u) # specify [u]sername for connection
+		username="$OPTARG"
+		;;
+	v) # be [v]erbose and display what's going on
+		verbose=""
+		tarargs=${tarargs}v
+		;;
+	'?') # any other switch
+		Usage 2 "Invalid switch specified - abort."
+		;;
+	esac
 done
 
-shift `expr $OPTIND - 1`
+shift $(expr $OPTIND - 1)
 
 if [ "$server" = "" ] || [ "$service" = "" ]; then
-  Usage 1 "No server or no service specified - abort."
+	Usage 1 "No server or no service specified - abort."
 fi
 
 # if the -v switch is set, the echo the current parameters
 if [ -z "$verbose" ]; then
-      echo "server    is $server"
-#     echo "share     is $service"
-      echo "share     is $service\\$cdcmd"
-      echo "tar args  is $tarargs"
-#     echo "password  is $password"  # passwords should never be sent to screen
-      echo "tape      is $tapefile"
-      echo "blocksize is $blocksize"
+	echo "server    is $server"
+#	echo "share     is $service"
+	echo "share     is $service\\$cdcmd"
+	echo "tar args  is $tarargs"
+#	echo "password  is $password"  # passwords should never be sent to screen
+	echo "tape      is $tapefile"
+	echo "blocksize is $blocksize"
 fi
 
 tarargs=${tarargs}${blocksizearg}${newerarg}
 
 eval $SMBCLIENT "'\\\\$server\\$service'" "'$password'" -U "'$username'" \
--E $log -D "'$cdcmd'" ${clientargs} \
--T${tarcmd}${tarargs} $blocksize $newer $tapefile '${1+"$@"}' $verbose
+	-E $log -D "'$cdcmd'" ${clientargs} \
+	-T${tarcmd}${tarargs} $blocksize $newer $tapefile '${1+"$@"}' $verbose
