s3: Allow pam_winbind.c to build without localedir.c
Signed-off-by: Stefan Metzmacher <metze@samba.org>

diff --git a/source3/Makefile.in b/source3/Makefile.in
--- a/source3/Makefile.in
+++ b/source3/Makefile.in
@@ -921,7 +921,7 @@ RPCCLIENT_OBJ = $(RPCCLIENT_OBJ1) \
 	     $(LIBADS_OBJ) $(POPT_LIB_OBJ) \
 	     $(SMBLDAP_OBJ) $(DCUTIL_OBJ) $(LDB_OBJ) 
 
-PAM_WINBIND_OBJ = ../nsswitch/pam_winbind.o localedir.o $(WBCOMMON_OBJ) \
+PAM_WINBIND_OBJ = ../nsswitch/pam_winbind.o $(WBCOMMON_OBJ) \
 		  $(LIBREPLACE_OBJ) @BUILD_INIPARSER@
 
 LIBSMBCLIENT_THREAD_OBJ = \
@@ -1516,6 +1516,13 @@ BINARY_PREREQS = bin/.dummy
 # rebuild it's a bit hard.
 
 dynconfig.o: dynconfig.c Makefile
+	@echo Compiling $*.c
+	@$(COMPILE_CC_PATH) && exit 0;\
+		echo "The following command failed:" 1>&2;\
+		echo "$(COMPILE_CC_PATH)" 1>&2;\
+		$(COMPILE_CC_PATH) >/dev/null 2>&1
+
+../nsswitch/pam_winbind.o: ../nsswitch/pam_winbind.c Makefile
 	@echo Compiling $*.c
 	@$(COMPILE_CC_PATH) && exit 0;\
 		echo "The following command failed:" 1>&2;\
