Run autoconf.  Shouldn't we have an autogen.sh here? (This used to be commit a43fe8e5f0cc95a8fb89db4ab1ee051b8c9d1bab)

diff --git a/docs/docbook/configure b/docs/docbook/configure
--- a/docs/docbook/configure
+++ b/docs/docbook/configure
@@ -557,10 +557,13 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
+if test "x$JW" = x; then
+   { echo "configure: error: "jw is required"" 1>&2; exit 1; }
+fi
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:564: checking for $ac_word" >&5
+echo "configure:567: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_PERL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -592,10 +595,13 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
+if test "x$PERL" = x; then
+   { echo "configure: error: "perl is required"" 1>&2; exit 1; }
+fi
 # Extract the first word of "htmldoc", so it can be a program name with args.
 set dummy htmldoc; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:599: checking for $ac_word" >&5
+echo "configure:605: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_HTMLDOC'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -627,6 +633,9 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
+if test "x$HTMLDOC" = x; then
+   { echo "configure: error: "htmldoc is required"" 1>&2; exit 1; }
+fi
 
 DOC_BUILD_DATE=`date '+%d-%m-%Y'`
 
