Merge over book changes into 3_0 CVS (This used to be commit d8fe4a81fb0d4972b2331b3d5fc4890244b44c33)

diff --git a/docs/docbook/configure b/docs/docbook/configure
--- a/docs/docbook/configure
+++ b/docs/docbook/configure
@@ -271,7 +271,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="global.ent"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS XSLTPROC PDFLATEX XMLTO LATEX DVIPS PNGTOPNM PNMTOPS DOC_BUILD_DATE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS XSLTPROC PDFLATEX MAKEINDEX LATEX DVIPS PNGTOPNM PNMTOPS DOC_BUILD_DATE TEXSTYLESHEET PAPERSIZE DUPLICATE_ULINKS FONTSIZE CROP LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -779,6 +779,17 @@ if test -n "$ac_init_help"; then
 
   cat <<\_ACEOF
 
+Optional Features:
+  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
+  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
+ --enable-crop					    Whether to use a crop template
+
+Optional Packages:
+  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
+  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+ --with-papersize					Specify papersize (a4paper,letter)
+ --with-fontsize	              Specify the fontsize in points (default: 10.5)
+
 _ACEOF
 fi
 
@@ -1031,7 +1042,7 @@ _ASBOX
       echo "$as_me: caught signal $ac_signal"
     echo "$as_me: exit $exit_status"
   } >&5
-  rm -f core core.* *.core &&
+  rm -f core *.core &&
   rm -rf conftest* confdefs* conf$$* $ac_clean_files &&
     exit $exit_status
      ' 0
@@ -1271,17 +1282,16 @@ if test "x$PDFLATEX" = x; then
 echo "$as_me: error: \"pdflatex is required\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
-
-# Extract the first word of "xmlto", so it can be a program name with args.
-set dummy xmlto; ac_word=$2
+# Extract the first word of "makeindex", so it can be a program name with args.
+set dummy makeindex; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_XMLTO+set}" = set; then
+if test "${ac_cv_path_MAKEINDEX+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $XMLTO in
+  case $MAKEINDEX in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_XMLTO="$XMLTO" # Let the user override the test with a path.
+  ac_cv_path_MAKEINDEX="$MAKEINDEX" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -1291,7 +1301,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_XMLTO="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_MAKEINDEX="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -1301,15 +1311,51 @@ done
   ;;
 esac
 fi
-XMLTO=$ac_cv_path_XMLTO
+MAKEINDEX=$ac_cv_path_MAKEINDEX
 
-if test -n "$XMLTO"; then
-  echo "$as_me:$LINENO: result: $XMLTO" >&5
-echo "${ECHO_T}$XMLTO" >&6
+if test -n "$MAKEINDEX"; then
+  echo "$as_me:$LINENO: result: $MAKEINDEX" >&5
+echo "${ECHO_T}$MAKEINDEX" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
+
+if test "x$MAKEINDEX" = x; then
+	{ { echo "$as_me:$LINENO: error: \"makeindex is required\"" >&5
+echo "$as_me: error: \"makeindex is required\"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+PAPERSIZE=""
+TEXSTYLESHEET=xslt/latex.xsl
+DUPLICATE_ULINKS=""
+
+CROP="--stringparam docrop 0"
+
+# Check whether --enable-crop or --disable-crop was given.
+if test "${enable_crop+set}" = set; then
+  enableval="$enable_crop"
+   test "$withval" && CROP="--stringparam docrop 1"
+fi;
+
+PAPERSIZE="--stringparam papersize a4paper"
+
+
+# Check whether --with-papersize or --without-papersize was given.
+if test "${with_papersize+set}" = set; then
+  withval="$with_papersize"
+   test "$withval" && PAPERSIZE="--stringparam papersize $withval"
+fi;
+
+FONTSIZE="--stringparam fontsize 10.5"
+
+
+# Check whether --with-fontsize or --without-fontsize was given.
+if test "${with_fontsize+set}" = set; then
+  withval="$with_fontsize"
+   test "$withval" && FONTSIZE="--stringparam fontsize $withval"
+fi;
 
 # Extract the first word of "latex", so it can be a program name with args.
 set dummy latex; ac_word=$2
@@ -1469,6 +1515,11 @@ fi
 
 
 DOC_BUILD_DATE=`date '+%d-%m-%Y'`
+
+
+
+
+
 
 
           ac_config_files="$ac_config_files Makefile"
@@ -2107,12 +2158,17 @@ s,@ECHO_T@,$ECHO_T,;t t
 s,@LIBS@,$LIBS,;t t
 s,@XSLTPROC@,$XSLTPROC,;t t
 s,@PDFLATEX@,$PDFLATEX,;t t
-s,@XMLTO@,$XMLTO,;t t
+s,@MAKEINDEX@,$MAKEINDEX,;t t
 s,@LATEX@,$LATEX,;t t
 s,@DVIPS@,$DVIPS,;t t
 s,@PNGTOPNM@,$PNGTOPNM,;t t
 s,@PNMTOPS@,$PNMTOPS,;t t
 s,@DOC_BUILD_DATE@,$DOC_BUILD_DATE,;t t
+s,@TEXSTYLESHEET@,$TEXSTYLESHEET,;t t
+s,@PAPERSIZE@,$PAPERSIZE,;t t
+s,@DUPLICATE_ULINKS@,$DUPLICATE_ULINKS,;t t
+s,@FONTSIZE@,$FONTSIZE,;t t
+s,@CROP@,$CROP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
