r9562: successfully get the samba 3 smbtorture working (as a test case for infrastructre) (This used to be commit c64f5666b8d1f9fb617b1cf89d6157a0c3fa9da9)

diff --git a/source3/script/tests/functions b/source3/script/tests/functions
--- a/source3/script/tests/functions
+++ b/source3/script/tests/functions
@@ -40,3 +40,43 @@ stop_smbd()
 	fi
 }
 
+
+##
+## start/stop smbd daemon
+##
+check_nmbd_running()
+{
+	## the smbcontrol ping will return a 0 on success
+	smbcontrol $CONFIGURATION nmbd ping 2>&1 > /dev/null
+}
+
+start_nmbd()
+{
+	echo "Starting nmbd...."
+
+	nmbd $CONFIGURATION || return $?
+
+	sleep 1
+
+	# smbcontrol $CONFIGURATION `cat $PIDDIR/nmbd.pid` ping 2>&1 > /dev/null || return $?
+	kill -0 `cat $PIDDIR/nmbd.pid`
+}
+
+stop_nmbd()
+{
+	nmbd_pid=`cat $PIDDIR/nmbd.pid`
+	echo "Shutting down nmbd (pid $nmbd_pid)..."
+
+	## belt and braces; first kill and then send a shutdown message
+
+	kill -TERM $nmbd_pid 2> /dev/null
+	sleep 1
+
+	## check to see if smbd is already running
+	kill -0 $nmbd_pid 2> /dev/null
+	if test $? == 0; then
+		echo "Unable to stop nmbd!"
+		exit 2
+	fi
+}
+
