r9548: more additions to make test; better checks for starting and stopping smbd (This used to be commit dbaaf81cec59aae01e71bbb639e1937ebee2454d)

diff --git a/source3/script/tests/functions b/source3/script/tests/functions
--- a/source3/script/tests/functions
+++ b/source3/script/tests/functions
@@ -2,3 +2,41 @@
 ## library file for test functions
 ##
 
+##
+## start/stop smbd daemon
+##
+check_smbd_running()
+{
+	## the smbcontrol ping will return a 0 on success
+	smbcontrol $CONFIGURATION smbd ping 2>&1 > /dev/null
+}
+
+start_smbd()
+{
+	echo "Starting smbd...."
+
+	smbd $CONFIGURATION || return $?
+
+	sleep 1
+
+	smbcontrol $CONFIGURATION `cat $PIDDIR/smbd.pid` ping 2>&1 > /dev/null || return $?
+}
+
+stop_smbd()
+{
+	smbd_pid=`cat $PIDDIR/smbd.pid`
+	echo "Shutting down smbd (pid $smbd_pid)..."
+
+	## belt and braces; first kill and then send a shutdown message
+
+	kill -TERM $smbd_pid
+	smbcontrol $CONFIGURATION smbd shutdown
+
+	## check to see if smbd is already running
+	check_smbd_running
+	if test $? == 0; then
+		echo "Unable to stop smbd!"
+		exit 2
+	fi
+}
+
