try generate a couple of rsa keys of diffrent (random) sizes, spelling.
git-svn-id: svn://svn.h5l.se/heimdal/trunk/heimdal@20462 ec53bebd-3082-4978-b11e-865c3cabbd6b

diff --git a/lib/des/test_crypto.in b/lib/des/test_crypto.in
--- a/lib/des/test_crypto.in
+++ b/lib/des/test_crypto.in
@@ -46,13 +46,14 @@ ${rsa} --key=${srcdir}/rsakey.der || \
 ${engine} --rsa=${srcdir}/rsakey.der || \
 	{ echo "engine test failed" ; exit 1; }
 
+${rsa} --loops=4 || { echo "rsa test for 4 loops failed" ; exit 1; }
 
 for a in unix fortuna egd ;do
 	${rand} --method=${a} crypto-test 2>error
 	res=$?
 	if test "X$res" != X0 ; then
 	    grep "random not ready yet" error || exit 1
-	    echo "random metod $a out for lunch"
+	    echo "random method $a out for lunch"
 	    continue
 	fi
 	${rand} --method=${a} crypto-test2 2>error
