ctdb-tests: Add unit tests for 46.update-keytabs.script
Update the net stub so it does option checking for "net ads keytab
create".

The net stub appears to have been unused since commit
6b75d2c650aa9ee632122fa87ea8a2a98f1fa613 in 2018, so these changes do
not affect any other event script unit tests.

BUG: https://bugzilla.samba.org/show_bug.cgi?id=16267

Signed-off-by: Martin Schwenke <mschwenke@ddn.com>
Reviewed-by: Pavel Filipenský <pfilipensky@samba.org>

diff --git a/ctdb/tests/UNIT/eventscripts/stubs/net b/ctdb/tests/UNIT/eventscripts/stubs/net
--- a/ctdb/tests/UNIT/eventscripts/stubs/net
+++ b/ctdb/tests/UNIT/eventscripts/stubs/net
@@ -1,5 +1,56 @@
 #!/bin/sh
 
-# Always succeed for now...
+prog=$(basename "$0")
+
+usage()
+{
+	cat <<EOF
+usage: ${prog} <command>
+commands:
+    ads keytab create [--option=<option>] [--configfile=<file>]
+options:
+    sync machine password script=
+EOF
+	exit 1
+}
+
+ads_keytab_create()
+{
+	for _opt; do
+		case "$_opt" in
+		--option=*)
+			_val="${_opt#*=}"
+			case "$_val" in
+			sync\ machine\ password\ script=)
+				:
+				;;
+			*)
+				usage
+				;;
+			esac
+			;;
+		--configfile=*)
+			_val="${_opt#*=}"
+			if [ ! -r "$_val" ]; then
+				echo "${prog}: error reading ${_val}"
+				exit 1
+			fi
+			;;
+		*)
+			usage
+			;;
+		esac
+	done
+}
+
+case "$*" in
+ads\ keytab\ create\ *)
+	shift 3
+	ads_keytab_create "$@"
+	;;
+*)
+	usage
+	;;
+esac
 
 exit 0
