ctdb-scripts: Only consider statistics on timeout
Checking statistics is only really relevant to timeouts.  That is, if
an rpcinfo times out it is worth checking if the service making
progress.  If the RPC service is not registered then the statistics
don't need to be checked because they shouldn't be changing.

The 2 previously added tests added to check statistics progress now
behave identically and fail on all iterations.  To support testing
with "timeouts", an optional TIMEOUT flag can now be added to the RPC
service passed to nfs_iterate_test().  2 new tests are added to
exercise the new behaviour.

The 2 new "if" statements in nfs_iterate_test() could be combined.
However, a subsequent commit would split them and would be more
difficult to read.

Signed-off-by: Martin Schwenke <mschwenke@ddn.com>
Reviewed-by: Amitay Isaacs <amitay@gmail.com>

diff --git a/ctdb/tests/UNIT/eventscripts/stubs/rpcinfo b/ctdb/tests/UNIT/eventscripts/stubs/rpcinfo
--- a/ctdb/tests/UNIT/eventscripts/stubs/rpcinfo
+++ b/ctdb/tests/UNIT/eventscripts/stubs/rpcinfo
@@ -40,6 +40,8 @@ parse_options()
 
 parse_options "$@"
 
+_fail_msg="rpcinfo: RPC: Program not registered"
+
 for i in ${FAKE_RPCINFO_SERVICES}; do
 	# This is stupidly cumulative, but needs to happen after the
 	# initial split of the list above.
@@ -47,9 +49,16 @@ for i in ${FAKE_RPCINFO_SERVICES}; do
 	# Want glob expansion
 	# shellcheck disable=SC2086
 	set -- $i
-	# $1 = program, $2 = low version, $3 = high version
+	# $1 = program, $2 = low version, $3 = high version, $4 = flag
 
 	if [ "$1" = "$p" ]; then
+		case "$4" in
+		TIMEOUT)
+			_fail_msg="rpcinfo: RPC: Timed out"
+			break
+			;;
+		esac
+
 		if [ -n "$v" ]; then
 			if [ "$2" -le "$v" ] && [ "$v" -le "$3" ]; then
 				echo "program ${p} version ${v} ready and waiting"
@@ -68,7 +77,7 @@ for i in ${FAKE_RPCINFO_SERVICES}; do
 	fi
 done
 
-echo "rpcinfo: RPC: Program not registered" >&2
+echo "$_fail_msg" >&2
 if [ -n "$v" ]; then
 	echo "program ${p} version ${v} is not available"
 else
