Make failing to compile a java program a no-fatal error.
git-svn-id: svn://svn.h5l.se/heimdal/trunk/heimdal@21601 ec53bebd-3082-4978-b11e-865c3cabbd6b

diff --git a/tests/java/check-kinit.in b/tests/java/check-kinit.in
--- a/tests/java/check-kinit.in
+++ b/tests/java/check-kinit.in
@@ -57,7 +57,8 @@ rm -f out-*
 rm -f mkey.file*
 
 echo "Compile"
-javac -d "${objdir}" "${srcdir}/KerberosInit.java" || exit 1
+javac -d "${objdir}" "${srcdir}/KerberosInit.java" || \
+    { echo "Failed to compile java program: $?" ; exit 77; }
 
 echo Creating database
 ${kadmin} \
