ctdb-scripts: Avoid shellcheck warnings SC2046, SC2086 (double-quoting)
SC2046: Quote this to prevent word splitting.
SC2086: Double quote to prevent globbing and word splitting.

Add some quoting where it makes sense.  Use shellcheck directives for
false-positives.

Signed-off-by: Martin Schwenke <martin@meltin.net>
Reviewed-by: Amitay Isaacs <amitay@gmail.com>

diff --git a/ctdb/tools/ctdb_diagnostics b/ctdb/tools/ctdb_diagnostics
--- a/ctdb/tools/ctdb_diagnostics
+++ b/ctdb/tools/ctdb_diagnostics
@@ -57,7 +57,7 @@ esac
 # them to $bad_nodes.
 _nodes=""
 for _i in $nodes ; do
-    if onnode $_i true >/dev/null 2>&1 ; then
+    if onnode "$_i" true >/dev/null 2>&1 ; then
 	_nodes="${_nodes}${_nodes:+ }${_i}"
     else
 	bad_nodes="${bad_nodes}${bad_nodes:+,}${_i}"
@@ -65,7 +65,7 @@ for _i in $nodes ; do
 done
 nodes="$_nodes"
 
-nodes_comma=$(echo $nodes | sed -e 's@[[:space:]]@,@g')
+nodes_comma=$(echo "$nodes" | sed -e 's@[[:space:]]@,@g')
 
 PATH="$PATH:/sbin:/usr/sbin:/usr/lpp/mmfs/bin"
 
@@ -97,21 +97,22 @@ error() {
     msg="$1"
     echo "ERROR: $msg"
     NUM_ERRORS=`expr $NUM_ERRORS + 1`
-    echo " ERROR[$NUM_ERRORS]: $msg" >> $ERRORS
+    echo " ERROR[$NUM_ERRORS]: $msg" >> "$ERRORS"
 }
 
 show_file() {
     fname="$1"
+    _fdetails=$(ls -l "$fname" 2>&1)
     echo "  ================================"
     echo "  File: $fname"
-    echo "  `ls -l $fname 2>&1`"
+    echo "  $_fdetails"
     cat "$fname" 2>&1 | sed 's/^/  /'
     echo "  ================================"
 }
 
 show_all() {
     echo "running $1 on nodes $nodes_comma"
-    onnode $nodes_comma "hostname; date; $1 2>&1 | sed 's/^/  /'" 2>&1
+    onnode "$nodes_comma" "hostname; date; $1 2>&1 | sed 's/^/  /'" 2>&1
 }
 
 show_and_compare_files () {
@@ -119,19 +120,20 @@ show_and_compare_files () {
     fmt="$1" ; shift
 
     for f ; do
+	_bf=$(basename "$f")
 	first=true
 
 	for n in $nodes ; do
 
 	    if $first ; then
-		onnode $n [ -r "$f" ] || {
-		    msg=$(printf "$fmt" "$f" $n)
+		onnode "$n" [ -r "$f" ] || {
+		    msg=$(printf "$fmt" "$f" "$n")
 		    error "$msg"
 		    continue 2;
 		}
 
-		fstf=$tmpdir/`basename $f`.node$n
-		onnode $n cat $f > $fstf 2>&1
+		fstf="${tmpdir}/${_bf}.node${n}"
+		onnode "$n" cat "$f" >"$fstf" 2>&1
 
 		echo "  ================================"
 		echo "  File (on node $n): $f"
@@ -141,17 +143,19 @@ show_and_compare_files () {
 		first=false
 	    else
 		echo "Testing for same config file $f on node $n"
-		tmpf=$tmpdir/`basename $f`.node$n
-		onnode $n cat $f > $tmpf 2>&1
-		diff $diff_opts $fstf $tmpf >/dev/null 2>&1 || {
+		tmpf="${tmpdir}/${_bf}.node${n}"
+		onnode "$n" cat "$f" >"$tmpf" 2>&1
+		# Intentional multi-word splitting on diff_opts
+		# shellcheck disable=SC2086
+		diff $diff_opts "$fstf" "$tmpf" >/dev/null 2>&1 || {
 		    error "File $f is different on node $n"
-		    diff -u $diff_opts $fstf $tmpf
+		    diff -u $diff_opts "$fstf" "$tmpf"
 		}
-		rm -f $tmpf
+		rm -f "$tmpf"
 	    fi
 	done
 
-	rm -f $fstf
+	rm -f "$fstf"
     done
 }
 
@@ -188,10 +192,14 @@ cat <<EOF
 Comping critical config files on nodes $nodes_comma
 EOF
 
+# Intentional multi-word splitting on CONFIG_FILES_MUST
+# shellcheck disable=SC2086
 show_and_compare_files \
     "%s is missing on node %d" \
     $CONFIG_FILES_MUST
 
+# Intentional multi-word splitting on CONFIG_FILES_MAY
+# shellcheck disable=SC2086
 show_and_compare_files \
     "Optional file %s is not present on node %d" \
     $CONFIG_FILES_MAY
@@ -202,9 +210,9 @@ Checking for clock drift
 EOF
 t=`date +%s`
 for i in $nodes; do
-    t2=`onnode $i date +%s`
+    t2=`onnode "$i" date +%s`
     d=`expr $t2 - $t`
-    if [ $d -gt 30 -o $d -lt -30 ]; then
+    if [ "$d" -gt 30 -o "$d" -lt -30 ]; then
 	error "time on node $i differs by $d seconds"
     fi
 done
@@ -324,9 +332,9 @@ show_all "smbd -b"
 date
 echo "Diagnostics finished with $NUM_ERRORS errors"
 
-[ -r $ERRORS ] && {
-    cat $ERRORS
-    rm -f $ERRORS
+[ -r "$ERRORS" ] && {
+    cat "$ERRORS"
+    rm -f "$ERRORS"
 }
 
 rm -rf "$tmpdir"
