test max-depth.
git-svn-id: svn://svn.h5l.se/heimdal/trunk/heimdal@21278 ec53bebd-3082-4978-b11e-865c3cabbd6b

diff --git a/lib/hx509/test_chain.in b/lib/hx509/test_chain.in
--- a/lib/hx509/test_chain.in
+++ b/lib/hx509/test_chain.in
@@ -103,6 +103,20 @@ ${hxtool} verify --missing-revoke \
 	chain:FILE:$srcdir/data/sub-ca.crt \
 	anchor:FILE:$srcdir/data/ca.crt > /dev/null || exit 1
 
+echo "max depth 2 (ok)"
+${hxtool} verify --missing-revoke \
+	--max-depth=2 \
+	cert:FILE:$srcdir/data/sub-cert.crt \
+	chain:FILE:$srcdir/data/sub-ca.crt \
+	anchor:FILE:$srcdir/data/ca.crt > /dev/null && exit 1
+
+echo "max depth 1 (fail)"
+${hxtool} verify --missing-revoke \
+	--max-depth=1 \
+	cert:FILE:$srcdir/data/sub-cert.crt \
+	chain:FILE:$srcdir/data/sub-ca.crt \
+	anchor:FILE:$srcdir/data/ca.crt > /dev/null && exit 1
+
 echo "ocsp non-ca responder"
 ${hxtool} verify \
     cert:FILE:$srcdir/data/test.crt \
