Test security layer in ntlm.
git-svn-id: svn://svn.h5l.se/heimdal/trunk/heimdal@19637 ec53bebd-3082-4978-b11e-865c3cabbd6b

diff --git a/tests/kdc/check-digest.in b/tests/kdc/check-digest.in
--- a/tests/kdc/check-digest.in
+++ b/tests/kdc/check-digest.in
@@ -143,6 +143,24 @@ ${context} --mech-type=ntlm \
 	    --name-type=hostbased-service datan@host.foo 2>/dev/null && \
 		{ echo "test_context 4 failed"; exit 1; }
 
+echo "Trying SL in NTLM"
+
+
+for type in \
+    "" \
+    "--getverifymic" \
+    "--wrapunwrap" \
+    "--getverifymic --wrapunwrap" \
+    ; do
+
+	echo "Trying NTLM type: ${type}"
+	${context} --mech-type=ntlm ${type} \
+	    --name-type=hostbased-service datan@TEST || \
+	    { echo "test_context 1 failed"; exit 1; }
+
+done
+
+
 echo "Trying CHAP"
 
 ${kdigest} digest-server-init \
