Try to detect another KDC running.
git-svn-id: svn://svn.h5l.se/heimdal/trunk/heimdal@17241 ec53bebd-3082-4978-b11e-865c3cabbd6b

diff --git a/tests/kdc/check-kdc.in b/tests/kdc/check-kdc.in
--- a/tests/kdc/check-kdc.in
+++ b/tests/kdc/check-kdc.in
@@ -91,6 +91,11 @@ ${kdc} &
 kdcpid=$!
 sleep 2
 
+if tail -1 messages.log | grep "No sockets" ; then
+    echo "The KDC failed to bind to any sockets, another KDC running ?"
+    exit 1
+fi
+
 exitcode=0
 
 echo "Getting client initial tickets"
