more hints about what can go wrong.
git-svn-id: svn://svn.h5l.se/heimdal/trunk/heimdal@21596 ec53bebd-3082-4978-b11e-865c3cabbd6b

diff --git a/tests/kdc/check-kadmin.in b/tests/kdc/check-kadmin.in
--- a/tests/kdc/check-kadmin.in
+++ b/tests/kdc/check-kadmin.in
@@ -96,12 +96,14 @@ fi
 
 trap "kill ${kdcpid} ${kadmpid}" EXIT
 
+echo "kinit"
 ${kinit} --password-file=${objdir}/foopassword \
     -S kadmin/admin@${R} foo/admin@${R} || exit 1
 
+echo "kadmin"
 env KRB5CCNAME=${cache} \
 ${kadmin} -p foo/admin@${R} add -p foo --use-defaults kaka@${R} || 
-	{ cat messages.log ; exit 1; }
+	{ echo "kadmin failed $?"; cat messages.log ; exit 1; }
 
 echo "killing kdc (${kdcpid} ${kadmpid})"
 kill ${kdcpid} ${kadmpid} > /dev/null 2>/dev/null
