added a configuration summary at the end of ./configure. It also aborts if essential functions are not available.

diff --git a/source/configure b/source/configure
--- a/source/configure
+++ b/source/configure
@@ -4892,6 +4892,28 @@ EOF
   fi
 fi
 
+echo "checking configure summary"
+if test "$cross_compiling" = yes; then
+    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
+else
+  cat > conftest.$ac_ext <<EOF
+#line 4901 "configure"
+#include "confdefs.h"
+#include "tests/summary.c"
+EOF
+if { (eval echo configure:4905: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest && (./conftest; exit) 2>/dev/null
+then
+  echo "configure OK";
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  echo ERROR - summary failure. Aborting config; exit 1
+fi
+rm -fr conftest*
+fi
+
+
 
 trap '' 1 2 15
 cat > confcache <<\EOF
